DROP DATABASE IF EXISTS musiciansdb;
CREATE DATABASE musiciansdb;
USE musiciansdb;

CREATE TABLE musician (
ID INT PRIMARY KEY AUTO_INCREMENT,
FName VARCHAR(64) NOT NULL,
LName VARCHAR(64) NOT NULL);

INSERT INTO musician (FName, LName) VALUES 
("Al", "Green"),
("Annie", "Lennox"),
("Aretha", "Franklin"),
("Art", "Garfunkel"),
("Axl", "Rose"),
("B.B.", "King"),
("Björk", "Guðmundsdóttir"),
("Bob", "Dylan"),
("Bob", "Marley"),
("Bobby", "Blue"),
("Bonnie", "Raitt"),
("Bono", "Hewson"),
("Brian", "Wilson"),
("Bruce", "Springsteen"),
("Buddy", "Holly"),
("Christina", "Aguilera"),
("Chuck", "Berry"),
("Curtis", "Mayfield"),
("Darlene", "Love"),
("David", "Bowie"),
("David", "Ruffin"),
("Celine", "Dion"),
("Dolly", "Parton"),
("Don", "Everly"),
("Don", "Henley"),
("Donny", "Hathaway"),
("Dusty", "Springfield"),
("Elton", "John"),
("Elvis", "Presley"),
("Eric", "Burdon"),
("Etta", "James"),
("Frankie", "Valli"),
("Freddie", "Mercury"),
("George", "Jones"),
("Gladys", "Knight"),
("Gregg", "Allman"),
("Hank", "Williams"),
("Howlin'", "Wolf"),
("Iggy", "Pop"),
("Jackie", "Wilson"),
("James", "Brown"),
("James", "Taylor"),
("Janis", "Joplin"),
("Jeff", "Buckley"),
("Jerry Lee", "Lewis"),
("Jim", "Morrison"),
("Joe", "Cocker"),
("John", "Fogerty"),
("John Lee", "Hooker"),
("John", "Lennon"),
("Johnny", "Cash"),
("Joni", "Mitchell"),
("Karen", "Carpenter"),
("Kurt", "Cobaine"),
("Levon", "Helm"),
("Little", "Richard"),
("Lou", "Reed"),
("Luther", "Vandross"),
("Mariah", "Carey"),
("Marvin", "Gaye"),
("Mary", "J.Blige"),
("Mavis", "Staples"),
("Merle", "Haggard"),
("Michael", "Jackson"),
("Mick", "Jagger"),
("Morrissey", "Steven"),
("Muddy", "Waters"),
("Neil", "Young"),
("Nina", "Simone"),
("Otis", "Redding"),
("Patsy", "Cline"),
("Patti", "LaBelle"),
("Patti", "Smith"),
("Paul", "McCartney"),
("Paul", "Rodgers"),
("Prince", "Nelson "),
("Ray", "Charles"),
("Robert", "Plant"),
("Rod", "Stewart"),
("Roger", "Daltrey"),
("Ronnie", "Spector"),
("Roy", "Orbison"),
("Sam", "Cooke"),
("Sam", "Moore"),
("Sly", "Stone"),
("Smokey", "Robinson"),
("Solomon", "Burke"),
("Steve", "Perry"),
("Steve", "Winwood"),
("Steven", "Tyler"),
("Stevie", "Nicks"),
("Stevie", "Wonder"),
("Thom", "Yorke"),
("Tina", "Turner"),
("Tom", "Waits"),
("Toots", "Hibbert"),
("Van", "Morrison"),
("Whitney", "Houston"),
("Willie", "Nelson"),
("Wilson", "Picket");